name: quran_daily
description: "A new Quran application as your companion."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  equatable: 2.0.5
  dio: 5.7.0
  logger: 2.4.0
  shared_preferences: 2.3.5
  kiwi: 5.0.1
  go_router:  14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Amiri_Quran
      fonts:
        - asset: assets/fonts/Amiri_Quran/AmiriQuran-Regular.ttf
